#!/usr/bin/env python3
"""
Update the version in __version__.py to match pyproject.toml.
Use this when bumping the library version.
"""

import re
from pathlib import Path


def update_version() -> None:
    root = Path(__file__).parent.parent

    pyproject_path = root / "pyproject.toml"
    content = pyproject_path.read_text()

    match = re.search(r'version\s*=\s*"([^"]+)"', content)
    if not match:
        raise ValueError("Could not find version in pyproject.toml")
    version = match.group(1)

    version_file = root / "src" / "dwellir_harvester" / "__version__.py"
    version_file.parent.mkdir(parents=True, exist_ok=True)
    version_file.write_text(
        f'# This file is auto-generated by {Path(__file__).name}. Do not edit manually.\\n'
        f'__version__ = "{version}"\\n'
    )
    print(f"Updated version to {version} in {version_file.relative_to(root)}")


if __name__ == "__main__":
    update_version()
